export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const CLEAR_LOGIN_INFO = 'CLEAR_LOGIN_INFO'
export const RECOVERY_USER = 'RECOVERY_USER'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'
export const IMPERSONATE_USER = 'IMPERSONATE_USER'
export const IMPERSONATE_USER_SUCCESS = 'IMPERSONATE_USER_SUCCESS'
export const IMPERSONATE_USER_ERROR = 'IMPERSONATE_USER_ERROR'

export const LOGIN_USER_OKTA = 'LOGIN_USER_OKTA'

export const GET_USER_DETAILS = 'GET_USER_DETAILS'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR'
export const PUT_USER_DETAILS = 'PUT_USER_DETAILS'
export const USER_DETAILS_CLEAR = 'USER_DETAILS_CLEAR'

export const GET_USER_SETTINGS = 'GET_USER_SETTINGS'
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS'
export const GET_USER_SETTINGS_ERROR = 'GET_USER_SETTINGS_ERROR'
export const USER_SETTINGS_CLEAR = 'GET_USER_SETTINGS_CLEAN'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_ACCESS = 'LOGOUT_USER_ACCESS'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'
export const CLEAR_LOGOUT_INFO = 'CLEAR_LOGOUT_INFO'

export const UPDATE_USER_TOKEN = 'UPDATE_USER_TOKEN'

export const UPDATE_TEMPLATE_CONTAINER = 'UPDATE_TEMPLATE_CONTAINER'
export const SET_TEMPLATE_CONTAINER_ORIENTATION =
  'SET_TEMPLATE_CONTAINER_ORIENTATION'
export const SET_TEMPLATE_CONTAINER_SIZE = 'SET_TEMPLATE_CONTAINER_SIZE'
export const SET_TEMPLATE_CONTAINER_VIDEO_WALL =
  'SET_TEMPLATE_CONTAINER_VIDEO_WALL'
export const SET_CURRENT_TEMPLATE_ITEM = 'SET_CURRENT_TEMPLATE_ITEM'
export const UPDATE_CURRENT_TEMPLATE_ITEM = 'UPDATE_CURRENT_TEMPLATE_ITEM'
export const SET_CURRENT_TEMPLATE_ITEM_SIZE = 'SET_CURRENT_TEMPLATE_ITEM_SIZE'
export const SET_CURRENT_TEMPLATE_ITEM_POSITION =
  'SET_CURRENT_TEMPLATE_ITEM_POSITION'
export const SET_CURRENT_TEMPLATE_ITEM_ALIGNMENT =
  'SET_CURRENT_TEMPLATE_ITEM_ALIGNMENT'
export const SET_CURRENT_TEMPLATE_ITEM_ROTATION =
  'SET_CURRENT_TEMPLATE_ITEM_ROTATION'
export const FLIP_CURRENT_TEMPLATE_ITEM = 'FLIP_CURRENT_TEMPLATE_ITEM'
export const DELETE_TEMPLATE_ITEMS = 'DELETE_TEMPLATE_ITEMS'
export const DELETE_TEMPLATE_ITEM = 'DELETE_TEMPLATE_ITEM'
export const ADD_TEMPLATE_ITEM = 'ADD_TEMPLATE_ITEM'
export const COPY_TEMPLATE_ITEM = 'COPY_TEMPLATE_ITEM'
export const MOVE_TEMPLATE_ITEM_FORWARD = 'MOVE_TEMPLATE_ITEM_FORWARD'
export const MOVE_TEMPLATE_ITEM_BACK = 'MOVE_TEMPLATE_ITEM_BACK'
export const ZOOM_IN_TEMPLATE_CONTAINER = 'ZOOM_IN_TEMPLATE_CONTAINER'
export const ZOOM_OUT_TEMPLATE_CONTAINER = 'ZOOM_OUT_TEMPLATE_CONTAINER'
export const LOCK_TEMPLATE_ITEM = 'LOCK_TEMPLATE_ITEM'
export const UNLOCK_TEMPLATE_ITEM = 'UNLOCK_TEMPLATE_ITEM'
export const TOGGLE_TEMPLATE_ITEM_TO_SELECTED =
  'TOGGLE_TEMPLATE_ITEM_TO_SELECTED'
export const CLEAR_SELECTED_ITEMS = 'CLEAR_SELECTED_ITEMS'
export const SET_MULTIPLIER = 'SET_MULTIPLIER'

export const ADD_MEDIA = 'ADD_MEDIA'
export const ADD_MEDIA_SUCCESS = 'ADD_MEDIA_SUCCESS'
export const ADD_MEDIA_ERROR = 'ADD_MEDIA_ERROR'
export const PUT_MEDIA = 'PUT_MEDIA'
export const PUT_MEDIA_SUCCESS = 'PUT_MEDIA_SUCCESS'
export const CLEAR_MEDIA_PUT = 'CLEAR_MEDIA_PUT'
export const PUT_MEDIA_ERROR = 'PUT_MEDIA_ERROR'
export const CREAR_MEDIA_ITEM = 'CREAR_MEDIA_ITEM'
export const CLEAR_MEDIA_ITEM_STATUS = 'CLEAR_MEDIA_ITEM_STATUS'
export const GET_MEDIA_ITEM_BY_ID = 'GET_MEDIA_ITEM_BY_ID'
export const GET_MEDIA_ITEM_BY_ID_SUCCESS = 'GET_MEDIA_ITEM_BY_ID_SUCCESS'
export const GET_MEDIA_ITEM_BY_ID_ERROR = 'GET_MEDIA_ITEM_BY_ID_ERROR'

export const CLEAR_ADDED_MEDIA = 'CLEAR_ADDED_MEDIA'
export const GET_MEDIA_ITEMS = 'GET_MEDIA_ITEMS'
export const GET_MEDIA_ITEMS_SUCCESS = 'GET_MEDIA_ITEMS_SUCCESS'
export const GET_MEDIA_ITEMS_ERROR = 'GET_MEDIA_ITEMS_ERROR'
export const CLEAR_MEDIA_ITEMS = 'CLEAR_MEDIA_ITEMS'
export const CLEAR_GET_MEDIA_ITEMS_INFO = 'CLEAR_GET_MEDIA_ITEMS_INFO'
export const GET_MEDIA_PREFERENCE = 'GET_MEDIA_PREFERENCE'
export const GET_MEDIA_PREFERENCE_SUCCESS = 'GET_MEDIA_PREFERENCE_SUCCESS'
export const GET_MEDIA_PREFERENCE_ERROR = 'GET_MEDIA_PREFERENCE_ERROR'
export const PUT_MEDIA_PREFERENCE = 'PUT_MEDIA_PREFERENCE'
export const PUT_MEDIA_PREFERENCE_SUCCESS = 'PUT_MEDIA_PREFERENCE_SUCCESS'
export const PUT_MEDIA_PREFERENCE_ERROR = 'PUT_MEDIA_PREFERENCE_ERROR'
export const GET_MEDIA_GROUPS = 'GET_MEDIA_GROUPS'
export const GET_MEDIA_GROUPS_SUCCESS = 'GET_MEDIA_GROUPS_SUCCESS'
export const GET_MEDIA_GROUPS_ERROR = 'GET_MEDIA_GROUPS_ERROR'
export const GET_MEDIA_PREVIEW = 'GET_MEDIA_PREVIEW'
export const GET_MEDIA_PREVIEW_SUCCESS = 'GET_MEDIA_PREVIEW_SUCCESS'
export const GET_MEDIA_PREVIEW_ERROR = 'GET_MEDIA_PREVIEW_ERROR'
export const CLOSE_MEDIA_PREVIEW = 'CLOSE_MEDIA_PREVIEW'
export const SHOW_MEDIA_PREVIEW = 'SHOW_MEDIA_PREVIEW'
export const GENERATE_MEDIA_PREVIEW = 'GENERATE_MEDIA_PREVIEW'
export const GENERATE_MEDIA_PREVIEW_SUCCESS = 'GENERATE_MEDIA_PREVIEW_SUCCESS'
export const GENERATE_MEDIA_PREVIEW_ERROR = 'GENERATE_MEDIA_PREVIEW_ERROR'
export const CLEAR_MEDIA_PREVIEW = 'CLEAR_MEDIA_PREVIEW'
export const CLEAR_GET_MEDIA_GROUPS_INFO = 'CLEAR_GET_MEDIA_GROUPS_INFO'
export const CLEAR_MEDIA_GROUP_ITEMS_RESPONSE_INFO =
  'CLEAR_MEDIA_GROUP_ITEMS_RESPONSE_INFO'
export const GET_MEDIA_GROUP_ITEMS = 'GET_MEDIA_GROUP_ITEMS'
export const CLEAR_GET_MEDIA_GROUP_ITEMS_INFO =
  'CLEAR_GET_MEDIA_GROUP_ITEMS_INFO'
export const POST_MEDIA_GROUP_ITEM = 'POST_MEDIA_GROUP_ITEM'
export const CLEAR_POST_MEDIA_GROUP_ITEM_INFO =
  'CLEAR_POST_MEDIA_GROUP_ITEM_INFO'
export const DELETE_MEDIA_GROUP_ITEM = 'DELETE_MEDIA_GROUP_ITEM'
export const CLEAR_DELETE_MEDIA_GROUP_ITEM_INFO =
  'CLEAR_DELETE_MEDIA_GROUP_ITEM_INFO'
export const GET_MEDIA_GROUP_ITEMS_SUCCESS = 'GET_MEDIA_GROUP_ITEMS_SUCCESS'
export const GET_MEDIA_GROUP_ITEMS_ERROR = 'GET_MEDIA_GROUP_ITEMS_ERROR'
export const POST_MEDIA_GROUP_ITEM_SUCCESS = 'POST_MEDIA_GROUP_ITEM_SUCCESS'
export const POST_MEDIA_GROUP_ITEM_ERROR = 'POST_MEDIA_GROUP_ITEM_ERROR'
export const DELETE_MEDIA_GROUP_ITEM_SUCCESS = 'DELETE_MEDIA_GROUP_ITEM_SUCCESS'
export const DELETE_MEDIA_GROUP_ITEM_ERROR = 'DELETE_MEDIA_GROUP_ITEM_ERROR'

export const CLEAR_ADDED_PLAYLIST = 'CLEAR_ADDED_PLAYLIST'
export const CLEAR_PLAYLIST_RESPONSE_INFO = 'CLEAR_PLAYLIST_RESPONSE_INFO'

export const CLONE_PLAYLIST = 'CLONE_PLAYLIST'
export const CLONE_PLAYLIST_SUCCESS = 'CLONE_PLAYLIST_SUCCESS'
export const CLONE_PLAYLIST_ERROR = 'CLONE_PLAYLIST_ERROR'

export const POST_PLAYLIST = 'POST_PLAYLIST'
export const POST_PLAYLIST_SUCCESS = 'POST_PLAYLIST_SUCCESS'
export const POST_PLAYLIST_ERROR = 'POST_PLAYLIST_ERROR'

export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS'
export const DELETE_PLAYLIST_ERROR = 'DELETE_PLAYLIST_ERROR'

export const DELETE_SELECTED_PLAYLIST = 'DELETE_SELECTED_PLAYLIST'
export const DELETE_SELECTED_PLAYLIST_SUCCESS =
  'DELETE_SELECTED_PLAYLIST_SUCCESS'
export const DELETE_SELECTED_PLAYLIST_ERROR = 'DELETE_SELECTED_PLAYLIST_ERROR'

export const GET_PLAYLIST_BY_ID = 'GET_PLAYLIST_BY_ID'
export const GET_PLAYLIST_BY_ID_SUCCESS = 'GET_PLAYLIST_BY_ID_SUCCESS'
export const GET_PLAYLIST_BY_ID_ERROR = 'GET_PLAYLIST_BY_ID_ERROR'
export const PUT_PLAYLIST = 'PUT_PLAYLIST'
export const PUT_PLAYLIST_SUCCESS = 'PUT_PLAYLIST_SUCCESS'
export const PUT_PLAYLIST_ERROR = 'PUT_PLAYLIST_ERROR'
export const GET_PLAYLIST_ITEMS = 'GET_PLAYLIST_ITEMS'
export const GET_PLAYLIST_ITEMS_SUCCESS = 'GET_PLAYLIST_ITEMS_SUCCESS'
export const GET_PLAYLIST_ITEMS_ERROR = 'GET_PLAYLIST_ITEMS_ERROR'
export const GET_PLAYLIST_PREFERENCE = 'GET_PLAYLIST_PREFERENCE'
export const GET_PLAYLIST_PREFERENCE_SUCCESS = 'GET_PLAYLIST_PREFERENCE_SUCCESS'
export const GET_PLAYLIST_PREFERENCE_ERROR = 'GET_PLAYLIST_PREFERENCE_ERROR'
export const PUT_PLAYLIST_PREFERENCE = 'PUT_PLAYLIST_PREFERENCE'
export const PUT_PLAYLIST_PREFERENCE_SUCCESS = 'PUT_PLAYLIST_PREFERENCE_SUCCESS'
export const PUT_PLAYLIST_PREFERENCE_ERROR = 'PUT_PLAYLIST_PREFERENCE_ERROR'
export const GET_PLAYLIST_GROUPS = 'GET_PLAYLIST_GROUPS'
export const GET_PLAYLIST_GROUPS_SUCCESS = 'GET_PLAYLIST_GROUPS_SUCCESS'
export const GET_PLAYLIST_GROUPS_ERROR = 'GET_PLAYLIST_GROUPS_ERROR'
export const CLEAR_GET_PLAYLIST_GROUP_INFO = 'CLEAR_GET_PLAYLIST_GROUP_INFO'
export const GET_PLAYLIST_GROUP_ITEMS = 'GET_PLAYLIST_GROUP_ITEMS'
export const GET_PLAYLIST_GROUP_ITEMS_SUCCESS =
  'GET_PLAYLIST_GROUP_ITEMS_SUCCESS'
export const GET_PLAYLIST_GROUP_ITEMS_ERROR = 'GET_PLAYLIST_GROUP_ITEMS_ERROR'
export const CLEAR_GET_PLAYLIST_GROUP_ITEMS_INFO =
  'CLEAR_GET_PLAYLIST_GROUP_ITEMS_INFO'
export const CLEAR_PLAYLIST_GROUP_ITEMS_RESPONSE_INFO =
  'CLEAR_PLAYLIST_GROUP_ITEMS_RESPONSE_INFO'
export const POST_PLAYLIST_GROUP_ITEM = 'POST_PLAYLIST_GROUP_ITEM'
export const POST_PLAYLIST_GROUP_ITEM_SUCCESS =
  'POST_PLAYLIST_GROUP_ITEM_SUCCESS'
export const POST_PLAYLIST_GROUP_ITEM_ERROR = 'POST_PLAYLIST_GROUP_ITEM_ERROR'
export const CLEAR_POST_PLAYLIST_GROUP_ITEM_INFO =
  'CLEAR_POST_PLAYLIST_GROUP_ITEM_INFO'
export const DELETE_PLAYLIST_GROUP_ITEM = 'DELETE_PLAYLIST_GROUP_ITEM'
export const DELETE_PLAYLIST_GROUP_ITEM_SUCCESS =
  'DELETE_PLAYLIST_GROUP_ITEM_SUCCESS'
export const DELETE_PLAYLIST_GROUP_ITEM_ERROR =
  'DELETE_PLAYLIST_GROUP_ITEM_ERROR'
export const CLEAR_DELETE_PLAYLIST_GROUP_ITEM_INFO =
  'CLEAR_DELETE_PLAYLIST_GROUP_ITEM_INFO'

export const POST_TEMPLATE = 'POST_TEMPLATE'
export const POST_TEMPLATE_SUCCESS = 'POST_TEMPLATE_SUCCESS'
export const POST_TEMPLATE_ERROR = 'POST_TEMPLATE_ERROR'
export const GET_TEMPLATE = 'GET_TEMPLATE'
export const GET_TEMPLATE_SUCCESS = 'GET_TEMPLATE_SUCCESS'
export const GET_TEMPLATE_ERROR = 'GET_TEMPLATE_ERROR'
export const PUT_TEMPLATE = 'PUT_TEMPLATE'
export const PUT_TEMPLATE_SUCCESS = 'PUT_TEMPLATE_SUCCESS'
export const PUT_TEMPLATE_ERROR = 'PUT_TEMPLATE_ERROR'
export const CLEAR_TEMPLATE_ITEM = 'CLEAR_TEMPLATE_ITEM'

export const GET_TEMPLATE_ITEMS = 'GET_TEMPLATE_ITEMS'
export const GET_TEMPLATE_ITEMS_SUCCESS = 'GET_TEMPLATE_ITEMS_SUCCESS'
export const GET_TEMPLATE_ITEMS_ERROR = 'GET_TEMPLATE_ITEMS_ERROR'
export const GET_TEMPLATE_PREFERENCE = 'GET_TEMPLATE_PREFERENCE'
export const GET_TEMPLATE_PREFERENCE_SUCCESS = 'GET_TEMPLATE_PREFERENCE_SUCCESS'
export const GET_TEMPLATE_PREFERENCE_ERROR = 'GET_TEMPLATE_PREFERENCE_ERROR'
export const PUT_TEMPLATE_PREFERENCE = 'PUT_TEMPLATE_PREFERENCE'
export const RESET_TEMPLATE_CONTAINER = 'RESET_TEMPLATE_CONTAINER'
export const PUT_TEMPLATE_PREFERENCE_ERROR = 'PUT_TEMPLATE_PREFERENCE_ERROR'
export const GET_TEMPLATE_GROUPS = 'GET_TEMPLATE_GROUPS'
export const GET_TEMPLATE_GROUPS_SUCCESS = 'GET_TEMPLATE_GROUPS_SUCCESS'
export const GET_TEMPLATE_GROUPS_ERROR = 'GET_TEMPLATE_GROUPS_ERROR'
export const CLEAR_GET_TEMPLATE_GROUPS_INFO = 'CLEAR_GET_TEMPLATE_GROUPS_INFO'
export const GET_TEMPLATE_GROUP_ITEMS = 'GET_TEMPLATE_GROUP_ITEMS'
export const GET_TEMPLATE_GROUP_ITEMS_SUCCESS =
  'GET_TEMPLATE_GROUP_ITEMS_SUCCESS'
export const GET_TEMPLATE_GROUP_ITEMS_ERROR = 'GET_TEMPLATE_GROUP_ITEMS_ERROR'
export const CLEAR_GET_TEMPLATE_GROUP_ITEMS_INFO =
  'CLEAR_GET_TEMPLATE_GROUP_ITEMS_INFO'
export const POST_TEMPLATE_GROUP_ITEM = 'POST_TEMPLATE_GROUP_ITEM'
export const POST_TEMPLATE_GROUP_ITEM_SUCCESS =
  'POST_TEMPLATE_GROUP_ITEM_SUCCESS'
export const POST_TEMPLATE_GROUP_ITEM_ERROR = 'POST_TEMPLATE_GROUP_ITEM_ERROR'
export const CLEAR_POST_TEMPLATE_GROUP_ITEM_INFO =
  'CLEAR_POST_TEMPLATE_GROUP_ITEM_INFO'
export const DELETE_TEMPLATE_GROUP_ITEM = 'DELETE_TEMPLATE_GROUP_ITEM'
export const DELETE_TEMPLATE_GROUP_ITEM_SUCCESS =
  'DELETE_TEMPLATE_GROUP_ITEM_SUCCESS'
export const DELETE_TEMPLATE_GROUP_ITEM_ERROR =
  'DELETE_TEMPLATE_GROUP_ITEM_ERROR'
export const CLEAR_DELETE_TEMPLATE_GROUP_ITEM_INFO =
  'CLEAR_DELETE_TEMPLATE_GROUP_ITEM_INFO'
export const CLEAR_TEMPLATE_GROUP_ITEMS_RESPONSE_INFO =
  'CLEAR_TEMPLATE_GROUP_ITEMS_RESPONSE_INFO'

export const CLONE_TEMPLATE = 'CLONE_TEMPLATE'
export const CLONE_TEMPLATE_SUCCESS = 'CLONE_TEMPLATE_SUCCESS'
export const CLONE_TEMPLATE_ERROR = 'CLONE_TEMPLATE_ERROR'

export const DELETE_TEMPLATE = 'DELETE_TEMPLATE'
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS'
export const DELETE_TEMPLATE_ERROR = 'DELETE_TEMPLATE_ERROR'

export const DELETE_SELECTED_TEMPLATE = 'DELETE_SELECTED_TEMPLATE'
export const DELETE_SELECTED_TEMPLATE_SUCCESS =
  'DELETE_SELECTED_TEMPLATE_SUCCESS'
export const DELETE_SELECTED_TEMPLATE_ERROR = 'DELETE_SELECTED_TEMPLATE_ERROR'

export const CLEAR_TEMPLATE_RESPONSE_INFO = 'CLEAR_TEMPLATE_RESPONSE_INFO'

export const GET_SCHEDULE_ITEMS = 'GET_SCHEDULE_ITEMS'
export const GET_SCHEDULE_ITEMS_SUCCESS = 'GET_SCHEDULE_ITEMS_SUCCESS'
export const GET_SCHEDULE_ITEMS_ERROR = 'GET_SCHEDULE_ITEMS_ERROR'
export const GET_SCHEDULE_PREFERENCE = 'GET_SCHEDULE_PREFERENCE'
export const GET_SCHEDULE_PREFERENCE_SUCCESS = 'GET_SCHEDULE_PREFERENCE_SUCCESS'
export const GET_SCHEDULE_PREFERENCE_ERROR = 'GET_SCHEDULE_PREFERENCE_ERROR'
export const PUT_SCHEDULE_PREFERENCE = 'PUT_SCHEDULE_PREFERENCE'
export const PUT_SCHEDULE_PREFERENCE_ERROR = 'PUT_SCHEDULE_PREFERENCE_ERROR'
export const GET_SCHEDULE_GROUPS = 'GET_SCHEDULE_GROUPS'
export const GET_SCHEDULE_GROUPS_SUCCESS = 'GET_SCHEDULE_GROUPS_SUCCESS'
export const GET_SCHEDULE_GROUPS_ERROR = 'GET_SCHEDULE_GROUPS_ERROR'
export const CLEAR_GET_SCHEDULE_GROUPS_INFO = 'CLEAR_GET_SCHEDULE_GROUPS_INFO'
export const GET_SCHEDULE_GROUP_ITEMS = 'GET_SCHEDULE_GROUP_ITEMS'
export const GET_SCHEDULE_GROUP_ITEMS_SUCCESS =
  'GET_SCHEDULE_GROUP_ITEMS_SUCCESS'
export const GET_SCHEDULE_GROUP_ITEMS_ERROR = 'GET_SCHEDULE_GROUP_ITEMS_ERROR'
export const CLEAR_GET_SCHEDULE_GROUP_ITEMS_INFO =
  'CLEAR_GET_SCHEDULE_GROUP_ITEMS_INFO'
export const CLEAR_SCHEDULE_GROUP_ITEMS_RESPONSE_INFO =
  'CLEAR_SCHEDULE_GROUP_ITEMS_RESPONSE_INFO'
export const POST_SCHEDULE_GROUP_ITEM = 'POST_SCHEDULE_GROUP_ITEM'
export const POST_SCHEDULE_GROUP_ITEM_SUCCESS =
  'POST_SCHEDULE_GROUP_ITEM_SUCCESS'
export const POST_SCHEDULE_GROUP_ITEM_ERROR = 'POST_SCHEDULE_GROUP_ITEM_ERROR'
export const CLEAR_POST_SCHEDULE_GROUP_ITEM_INFO =
  'CLEAR_POST_SCHEDULE_GROUP_ITEM_INFO'
export const DELETE_SCHEDULE_GROUP_ITEM = 'DELETE_SCHEDULE_GROUP_ITEM'
export const DELETE_SCHEDULE_GROUP_ITEM_SUCCESS =
  'DELETE_SCHEDULE_GROUP_ITEM_SUCCESS'
export const DELETE_SCHEDULE_GROUP_ITEM_ERROR =
  'DELETE_SCHEDULE_GROUP_ITEM_ERROR'
export const CLEAR_DELETE_SCHEDULE_GROUP_ITEM_INFO =
  'CLEAR_DELETE_SCHEDULE_GROUP_ITEM_INFO'

export const DELETE_SELECTED_SCHEDULES = 'DELETE_SELECTED_SCHEDULES'
export const DELETE_SELECTED_SCHEDULES_SUCCESS =
  'DELETE_SELECTED_SCHEDULES_SUCCESS'
export const DELETE_SELECTED_SCHEDULES_ERROR = 'DELETE_SELECTED_SCHEDULES_ERROR'

export const DELETE_SCHEDULE = 'DELETE_SCHEDULE'
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS'
export const DELETE_SCHEDULE_ERROR = 'DELETE_SCHEDULE_ERROR'

export const CLONE_SCHEDULE = 'CLONE_SCHEDULE'
export const CLONE_SCHEDULE_SUCCESS = 'CLONE_SCHEDULE_SUCCESS'
export const CLONE_SCHEDULE_ERROR = 'CLONE_SCHEDULE_ERROR'

export const CLEAR_SCHEDULE_RESPONSE_INFO = 'CLEAR_SCHEDULE_RESPONSE_INFO'

export const GET_DEVICE_ITEMS = 'GET_DEVICE_ITEMS'
export const GET_DEVICE_ITEMS_SUCCESS = 'GET_DEVICE_ITEMS_SUCCESS'
export const GET_DEVICE_ITEMS_ERROR = 'GET_DEVICE_ITEMS_ERROR'
export const GET_DEVICE_PREFERENCE = 'GET_DEVICE_PREFERENCE'
export const GET_DEVICE_PREFERENCE_SUCCESS = 'GET_DEVICE_PREFERENCE_SUCCESS'
export const GET_DEVICE_PREFERENCE_ERROR = 'GET_DEVICE_PREFERENCE_ERROR'
export const PUT_DEVICE_PREFERENCE = 'PUT_DEVICE_PREFERENCE'
export const PUT_DEVICE_PREFERENCE_ERROR = 'PUT_DEVICE_PREFERENCE_ERROR'
export const GET_DEVICE_GROUPS = 'GET_DEVICE_GROUPS'
export const GET_DEVICE_GROUPS_SUCCESS = 'GET_DEVICE_GROUPS_SUCCESS'
export const GET_DEVICE_GROUPS_ERROR = 'GET_DEVICE_GROUPS_ERROR'
export const CLEAR_GET_DEVICE_GROUPS_INFO = 'CLEAR_GET_DEVICE_GROUPS_INFO'
export const PUT_DEVICE_ITEM = 'PUT_DEVICE_ITEM'
export const PUT_DEVICE_ITEM_SUCCESS = 'PUT_DEVICE_ITEM_SUCCESS'
export const PUT_DEVICE_ITEM_ERROR = 'PUT_DEVICE_ITEM_ERROR'
export const CLEAR_PUT_DEVICE_ITEM_INFO = 'CLEAR_PUT_DEVICE_ITEM_INFO'
export const GET_DEVICE_ITEM = 'GET_DEVICE_ITEM'
export const GET_DEVICE_ITEM_SUCCESS = 'GET_DEVICE_ITEM_SUCCESS'
export const GET_DEVICE_ITEM_ERROR = 'GET_DEVICE_ITEM_ERROR'
export const CLEAR_GET_DEVICE_ITEM_INFO = 'CLEAR_GET_DEVICE_ITEM_INFO'
export const GET_DEVICE_PREVIEW = 'GET_DEVICE_PREVIEW'
export const GET_DEVICE_PREVIEW_SUCCESS = 'GET_DEVICE_PREVIEW_SUCCESS'
export const GET_DEVICE_PREVIEW_ERROR = 'GET_DEVICE_PREVIEW_ERROR'
export const CLEAR_GET_DEVICE_PREVIEW_INFO = 'CLEAR_GET_DEVICE_PREVIEW_INFO'
export const GET_DEVICE_GROUP_ITEMS = 'GET_DEVICE_GROUP_ITEMS'
export const GET_DEVICE_GROUP_ITEMS_SUCCESS = 'GET_DEVICE_GROUP_ITEMS_SUCCESS'
export const GET_DEVICE_GROUP_ITEMS_ERROR = 'GET_DEVICE_GROUP_ITEMS_ERROR'
export const CLEAR_GET_DEVICE_GROUP_ITEMS_INFO =
  'CLEAR_GET_DEVICE_GROUP_ITEMS_INFO'
export const POST_DEVICE_GROUP_ITEM = 'POST_DEVICE_GROUP_ITEM'
export const POST_DEVICE_GROUP_ITEM_SUCCESS = 'POST_DEVICE_GROUP_ITEM_SUCCESS'
export const POST_DEVICE_GROUP_ITEM_ERROR = 'POST_DEVICE_GROUP_ITEM_ERROR'
export const CLEAR_POST_DEVICE_GROUP_ITEM_INFO =
  'CLEAR_POST_DEVICE_GROUP_ITEM_INFO'
export const DELETE_DEVICE_GROUP_ITEM = 'DELETE_DEVICE_GROUP_ITEM'
export const DELETE_DEVICE_GROUP_ITEM_SUCCESS =
  'DELETE_DEVICE_GROUP_ITEM_SUCCESS'
export const DELETE_DEVICE_GROUP_ITEM_ERROR = 'DELETE_DEVICE_GROUP_ITEM_ERROR'
export const CLEAR_DELETE_DEVICE_GROUP_ITEM_INFO =
  'CLEAR_DELETE_DEVICE_GROUP_ITEM_INFO'
export const CLEAR_DEVICE_GROUP_ITEMS_RESPONSE_INFO =
  'CLEAR_DEVICE_GROUP_ITEMS_RESPONSE_INFO'
export const GET_DEVICE_REBOOT = 'GET_DEVICE_REBOOT'
export const GET_DEVICE_REBOOT_SUCCESS = 'GET_DEVICE_REBOOT_SUCCESS'
export const GET_DEVICE_REBOOT_ERROR = 'GET_DEVICE_REBOOT_ERROR'
export const CLEAR_GET_DEVICE_REBOOT_INFO = 'CLEAR_GET_DEVICE_REBOOT_INFO'
export const PUT_DEVICE_REBOOT = 'PUT_DEVICE_REBOOT'
export const PUT_DEVICE_REBOOT_SUCCESS = 'PUT_DEVICE_REBOOT_SUCCESS'
export const PUT_DEVICE_REBOOT_ERROR = 'PUT_DEVICE_REBOOT_ERROR'
export const CLEAR_PUT_DEVICE_REBOOT_INFO = 'CLEAR_DEVICE_REBOOT_INFO'
export const GET_DEVICE_SLEEP_MODE = 'GET_DEVICE_SLEEP_MODE'
export const GET_DEVICE_SLEEP_MODE_SUCCESS = 'GET_DEVICE_SLEEP_MODE_SUCCESS'
export const GET_DEVICE_SLEEP_MODE_ERROR = 'GET_DEVICE_SLEEP_MODE_ERROR'
export const CLEAR_GET_DEVICE_SLEEP_MODE_INFO =
  'CLEAR_GET_DEVICE_SLEEP_MODE_INFO'
export const PUT_DEVICE_SLEEP_MODE = 'PUT_DEVICE_SLEEP_MODE'
export const PUT_DEVICE_SLEEP_MODE_SUCCESS = 'PUT_DEVICE_SLEEP_MODE_SUCCESS'
export const PUT_DEVICE_SLEEP_MODE_ERROR = 'PUT_DEVICE_SLEEP_MODE_ERROR'
export const CLEAR_PUT_DEVICE_SLEEP_MODE_INFO = 'CLEAR_DEVICE_SLEEP_MODE_INFO'

export const GET_DEVICE_NOTES = 'GET_DEVICE_NOTES'
export const GET_DEVICE_NOTES_SUCCESS = 'GET_DEVICE_NOTES_SUCCESS'
export const GET_DEVICE_NOTES_ERROR = 'GET_DEVICE_NOTES_ERROR'
export const POST_DEVICE_NOTE = 'POST_DEVICE_NOTE'
export const POST_DEVICE_NOTE_SUCCESS = 'POST_DEVICE_NOTE_SUCCESS'
export const POST_DEVICE_NOTE_ERROR = 'POST_DEVICE_NOTE_ERROR'

export const GET_REPORT_ITEMS = 'GET_REPORT_ITEMS'
export const GET_REPORT_ITEMS_SUCCESS = 'GET_REPORT_ITEMS_SUCCESS'
export const GET_REPORT_ITEMS_ERROR = 'GET_REPORT_ITEMS_ERROR'
export const DELETE_SELECTED_REPORTS = 'DELETE_SELECTED_REPORTS'
export const DELETE_SELECTED_REPORTS_SUCCESS = 'DELETE_SELECTED_REPORTS_SUCCESS'
export const DELETE_SELECTED_REPORTS_ERROR = 'DELETE_SELECTED_REPORTS_ERROR'
export const CLEAR_REPORT_RESPONSE_INFO = 'CLEAR_REPORT_RESPONSE_INFO'

//Client Actions
export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'
export const GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR'

export const GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID'
export const GET_CLIENT_BY_ID_SUCCESS = 'GET_CLIENT_BY_ID_SUCCESS'
export const GET_CLIENT_BY_ID_ERROR = 'GET_CLIENT_BY_ID_ERROR'

export const POST_CLIENT = 'POST_CLIENT'
export const POST_CLIENT_SUCCESS = 'POST_CLIENT_SUCCESS'
export const POST_CLIENT_ERROR = 'POST_CLIENT_ERROR'

export const PUT_CLIENT = 'PUT_CLIENT'
export const PUT_CLIENT_SUCCESS = 'PUT_CLIENT_SUCCESS'
export const PUT_CLIENT_ERROR = 'PUT_CLIENT_ERROR'

export const CLEAR_CLIENT_RESPONSE_INFO = 'CLEAR_CLIENT_RESPONSE_INFO'

export const GET_CLIENT_GROUP_ITEMS = 'GET_CLIENT_GROUP_ITEMS'
export const GET_CLIENT_GROUP_ITEMS_SUCCESS = 'GET_CLIENT_GROUP_ITEMS_SUCCESS'
export const GET_CLIENT_GROUP_ITEMS_ERROR = 'GET_CLIENT_GROUP_ITEMS_ERROR'

export const POST_CLIENT_GROUP_ITEM = 'POST_CLIENT_GROUP_ITEM'
export const POST_CLIENT_GROUP_ITEM_SUCCESS = 'POST_CLIENT_GROUP_ITEM_SUCCESS'
export const POST_CLIENT_GROUP_ITEM_ERROR = 'POST_CLIENT_GROUP_ITEM_ERROR'

export const DELETE_CLIENT_GROUP_ITEM = 'DELETE_CLIENT_GROUP_ITEM'
export const DELETE_CLIENT_GROUP_ITEM_SUCCESS =
  'DELETE_CLIENT_GROUP_ITEM_SUCCESS'
export const DELETE_CLIENT_GROUP_ITEM_ERROR = 'DELETE_CLIENT_GROUP_ITEM_ERROR'

export const CLEAR_CLIENT_GROUP_ITEMS_RESPONSE_INFO =
  'CLEAR_CLIENT_GROUP_ITEMS_RESPONSE_INFO'
export const CLEAR_GET_CLIENTS_GROUP_ITEMS_INFO =
  'CLEAR_GET_CLIENTS_GROUP_ITEMS_INFO'
export const GET_CLIENT_NOTES = 'GET_CLIENT_NOTES'
export const GET_CLIENT_NOTES_SUCCESS = 'GET_CLIENT_NOTES_SUCCESS'
export const GET_CLIENT_NOTES_ERROR = 'GET_CLIENT_NOTES_ERROR'
export const POST_CLIENT_NOTE = 'POST_CLIENT_NOTE'
export const POST_CLIENT_NOTE_SUCCESS = 'POST_CLIENT_NOTE_SUCCESS'
export const POST_CLIENT_NOTE_ERROR = 'POST_CLIENT_NOTE_ERROR'
export const CLEAR_GET_CLIENT_NOTE_INFO = 'CLEAR_GET_CLIENT_NOTE_INFO'
export const CLEAR_POST_CLIENT_NOTE_INFO = 'CLEAR_POST_CLIENT_NOTE_INFO'

//Users Actions
export const GET_USERS_ITEMS = 'GET_USERS_ITEMS'
export const GET_USERS_ITEMS_SUCCESS = 'GET_USERS_ITEMS_SUCCESS'
export const GET_USERS_ITEMS_ERROR = 'GET_USERS_ITEMS_ERROR'

export const POST_USERS_ITEM = 'POST_USERS_ITEM'
export const POST_USERS_ITEM_SUCCESS = 'POST_USERS_ITEM_SUCCESS'
export const POST_USERS_ITEM_ERROR = 'POST_USERS_ITEM_ERROR'

export const DELETE_USERS_ITEM = 'DELETE_USERS_ITEM'
export const DELETE_USERS_ITEM_SUCCESS = 'DELETE_USERS_ITEM_SUCCESS'
export const DELETE_USERS_ITEM_ERROR = 'DELETE_USERS_ITEM_ERROR'

export const DELETE_SELECTED_USERS = 'DELETE_SELECTED_USERS'
export const DELETE_SELECTED_USERS_SUCCESS = 'DELETE_SELECTED_USERS_SUCCESS'
export const DELETE_SELECTED_USERS_ERROR = 'DELETE_SELECTED_USERS_ERROR'

export const GET_USERS_ITEM = 'GET_USERS_ITEM'
export const GET_USERS_ITEM_SUCCESS = 'GET_USERS_ITEM_SUCCESS'
export const GET_USERS_ITEM_ERROR = 'GET_USERS_ITEM_ERROR'

export const PUT_USERS_ITEM = 'PUT_USERS_ITEM'
export const PUT_USERS_ITEM_SUCCESS = 'PUT_USERS_ITEM_SUCCESS'
export const PUT_USERS_ITEM_ERROR = 'PUT_USERS_ITEM_ERROR'

export const GET_USERS_GROUPS = 'GET_USERS_GROUPS'
export const GET_USERS_GROUPS_SUCCESS = 'GET_USERS_GROUPS_SUCCESS'
export const GET_USERS_GROUPS_ERROR = 'GET_USERS_GROUPS_ERROR'

export const GET_UNGROUPED_USERS = 'GET_UNGROUPED_USERS'
export const GET_UNGROUPED_USERS_SUCCESS = 'GET_UNGROUPED_USERS_SUCCESS'
export const GET_UNGROUPED_USERS_ERROR = 'GET_UNGROUPED_USERS_ERROR'

export const GET_USERS_GROUP_ITEMS = 'GET_USERS_GROUP_ITEMS'
export const GET_USERS_GROUP_ITEMS_SUCCESS = 'GET_USERS_GROUP_ITEMS_SUCCESS'
export const GET_USERS_GROUP_ITEMS_ERROR = 'GET_USERS_GROUP_ITEMS_ERROR'

export const POST_USERS_GROUP_ITEM = 'POST_USERS_GROUP_ITEM'
export const POST_USERS_GROUP_ITEM_SUCCESS = 'POST_USERS_GROUP_ITEM_SUCCESS'
export const POST_USERS_GROUP_ITEM_ERROR = 'POST_USERS_GROUP_ITEM_ERROR'

export const DELETE_USERS_GROUP_ITEM = 'DELETE_USERS_GROUP_ITEM'
export const DELETE_USERS_GROUP_ITEM_SUCCESS = 'DELETE_USERS_GROUP_ITEM_SUCCESS'
export const DELETE_USERS_GROUP_ITEM_ERROR = 'DELETE_USERS_GROUP_ITEM_ERROR'
export const CLEAR_GET_USERS_GROUP_ITEMS_INFO =
  'CLEAR_GET_USERS_GROUP_ITEMS_INFO'
export const CLEAR_USERS_GROUP_ITEMS_RESPONSE_INFO =
  'CLEAR_USERS_GROUP_ITEMS_RESPONSE_INFO'

export const GET_USERS_PERMISSION = 'GET_USERS_PERMISSION'
export const GET_USERS_PERMISSION_SUCCESS = 'GET_USERS_PERMISSION_SUCCESS'
export const GET_USERS_PERMISSION_ERROR = 'GET_USERS_PERMISSION_ERROR'

export const PUT_USERS_PERMISSION = 'PUT_USERS_PERMISSION'
export const PUT_USERS_PERMISSION_SUCCESS = 'PUT_USERS_PERMISSION_SUCCESS'
export const PUT_USERS_PERMISSION_ERROR = 'PUT_USERS_PERMISSION_ERROR'

export const GET_USERS_GROUP_PERMISSION = 'GET_USERS_GROUP_PERMISSION'
export const GET_USERS_GROUP_PERMISSION_SUCCESS =
  'GET_USERS_GROUP_PERMISSION_SUCCESS'
export const GET_USERS_GROUP_PERMISSION_ERROR =
  'GET_USERS_GROUP_PERMISSION_ERROR'

export const PUT_USERS_GROUP_PERMISSION = 'PUT_USERS_GROUP_PERMISSION'
export const PUT_USERS_GROUP_PERMISSION_SUCCESS =
  'PUT_USERS_GROUP_PERMISSION_SUCCESS'
export const PUT_USERS_GROUP_PERMISSION_ERROR =
  'PUT_USERS_GROUP_PERMISSION_ERROR'

export const CLEAR_USERS_RESPONSE_INFO = 'CLEAR_USERS_RESPONSE_INFO'
export const CLEAR_GET_USERS_PERMISSION_INFO = 'CLEAR_GET_USERS_PERMISSION_INFO'
export const CLEAR_GET_USERS_GROUP_PERMISSION_INFO =
  'CLEAR_GET_USERS_GROUP_PERMISSION_INFO'

//Dashboard Actions
export const GET_DASHBOARD_INFO = 'GET_DASHBOARD_INFO'
export const GET_DASHBOARD_INFO_SUCCESS = 'GET_DASHBOARD_INFO_SUCCESS'
export const GET_DASHBOARD_INFO_ERROR = 'GET_DASHBOARD_INFO_ERROR'

export const PUT_DASHBOARD_INFO = 'PUT_DASHBOARD_INFO'
export const PUT_DASHBOARD_INFO_SUCCESS = 'PUT_DASHBOARD_INFO_SUCCESS'
export const PUT_DASHBOARD_INFO_ERROR = 'PUT_DASHBOARD_INFO_ERROR'

export const POST_FEEDBACK = 'PUT_FEEDBACK'
export const POST_FEEDBACK_SUCCESS = 'PUT_FEEDBACK_SUCCESS'
export const POST_FEEDBACK_ERROR = 'PUT_FEEDBACK_ERROR'
export const CLEAR_POST_FEEDBACK = 'CLEAR_PUT_FEEDBACK'

//Tags Actions
export const GET_TAGS = 'GET_TAGS'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR'

export const GET_TAG_BY_ID = 'GET_TAG_BY_ID'
export const GET_TAG_BY_ID_SUCCESS = 'GET_TAG_BY_ID_SUCCESS'
export const GET_TAG_BY_ID_ERROR = 'GET_TAG_BY_ID_ERROR'

export const DELETE_TAG = 'DELETE_TAG'
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS'
export const DELETE_TAG_ERROR = 'DELETE_TAG_ERROR'

export const POST_TAG = 'POST_TAG'
export const POST_TAG_SUCCESS = 'POST_TAG_SUCCESS'
export const POST_TAG_ERROR = 'POST_TAG_ERROR'

export const PUT_TAG = 'PUT_TAG'
export const PUT_TAG_SUCCESS = 'PUT_TAG_SUCCESS'
export const PUT_TAG_ERROR = 'PUT_TAG_ERROR'

export const DELETE_SELECTED_TAGS = 'DELETE_SELECTED_TAGS'
export const DELETE_SELECTED_TAGS_SUCCESS =
  'DELETE_SELECTED_SELECTED_TAGS_SUCCESS'
export const DELETE_SELECTED_TAGS_ERROR = 'DELETE_SELECTED_TAGS_ERROR'

export const CLEAR_TAG_RESPONSE_INFO = 'CLEAR_TAG_RESPONSE_INFO'

export const GET_GROUPS_BY_ENTITY = 'GET_GROUPS_BY_ENTITY'
export const GET_GROUPS_BY_ENTITY_SUCCESS = 'GET_GROUPS_BY_ENTITY_SUCCESS'
export const GET_GROUPS_BY_ENTITY_ERROR = 'GET_GROUPS_BY_ENTITY_ERROR'

export const POST_GROUP = 'POST_DEVICE_GROUP'
export const POST_GROUP_SUCCESS = 'POST_DEVICE_GROUP_SUCCESS'
export const POST_GROUP_ERROR = 'POST_DEVICE_GROUP_ERROR'

export const CLEAR_POST_GROUP_INFO = 'CLEAR_POST_DEVICE_GROUP_INFO'
export const DELETE_GROUP = 'DELETE_GROUP'
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR'

export const CLEAR_DELETE_GROUP_INFO = 'CLEAR_DELETE_GROUP_INFO'

export const PUT_GROUP = 'PUT_GROUP'
export const PUT_GROUP_SUCCESS = 'PUT_GROUP_SUCCESS'
export const PUT_GROUP_ERROR = 'PUT_GROUP_ERROR'

export const CLEAR_PUT_GROUP_INFO = 'CLEAR_PUT_GROUP_INFO'

export const CLEAR_UPDATE_GROUP_INFO = 'CLEAR_UPDATE_GROUP_INFO'

export const GET_BACKGROUND_IMAGES = 'GET_BACKGROUND_IMAGES'
export const GET_BACKGROUND_IMAGES_SUCCESS = 'GET_BACKGROUND_IMAGES_SUCCESS'
export const GET_BACKGROUND_IMAGES_ERROR = 'GET_BACKGROUND_IMAGES_ERROR'

export const GET_PATTERNS = 'GET_PATTERNS'
export const GET_PATTERNS_SUCCESS = 'GET_PATTERNS_SUCCESS'

export const GET_SHAPES = 'GET_SHAPES'
export const GET_SHAPES_SUCCESS = 'GET_SHAPES_SUCCESS'

export const GET_ICONS = 'GET_ICONS'
export const GET_ICONS_SUCCESS = 'GET_ICONS_SUCCESS'

export const ADD_TEMPLATE = 'ADD_TEMPLATE'
export const ADD_TEMPLATE_SUCCESS = 'ADD_TEMPLATE_SUCCESS'
export const GET_TEMPLATES = 'GET_TEMPLATES'
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS'

export const GET_EMOJIS = 'GET_EMOJIS'
export const GET_EMOJIS_SUCCESS = 'GET_EMOJIS_SUCCESS'

export const SET_OPEN_LEFT_SIDEBAR = 'SET_OPEN_LEFT_SIDEBAR'

export const SET_SELECTED_BG = 'SET_SELECTED_BG'
export const SET_SELECTED_BG_SUCCESS = 'SET_SELECTED_BG_SUCCESS'

export const GET_STOCK_IMAGES = 'GET_STOCK_IMAGES'
export const GET_STOCK_IMAGES_SUCCESS = 'GET_STOCK_IMAGES_SUCCESS'
export const GET_STOCK_IMAGES_ERROR = 'GET_STOCK_IMAGES_ERROR'

export const GET_LIBRARY_IMAGES = 'GET_LIBRARY_IMAGES'
export const GET_LIBRARY_IMAGES_SUCCESS = 'GET_LIBRARY_IMAGES_SUCCESS'

export const GET_GROUP_PERMISSION = 'GET_GROUP_PERMISSION'
export const GET_GROUP_PERMISSION_SUCCESS = 'GET_GROUP_PERMISSION_SUCCESS'
export const GET_GROUP_PERMISSION_ERROR = 'GET_GROUP_PERMISSION_ERROR'
export const CLEAR_GET_GROUP_PERMISSION_INFO = 'CLEAR_GET_GROUP_PERMISSION_INFO'
export const PUT_GROUP_PERMISSION = 'PUT_GROUP_PERMISSION'
export const PUT_GROUP_PERMISSION_SUCCESS = 'PUT_GROUP_PERMISSION_SUCCESS'
export const PUT_GROUP_PERMISSION_ERROR = 'PUT_GROUP_PERMISSION_ERROR'
export const CLEAR_PUT_GROUP_PERMISSION_INFO = 'CLEAR_PUT_GROUP_PERMISSION_INFO'

export const GET_LOCATION = 'GET_LOCATION'
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR'
export const CLEAR_MEDIA_CATEGORY_CONFIG = 'CLEAR_MEDIA_CATEGORY_CONFIG'
//Config Actions
export const GET_CONFIG_ORG_ROLE = 'GET_CONFIG_ORG_ROLE'
export const GET_CONFIG_ORG_ROLE_SUCCESS = 'GET_CONFIG_ORG_ROLE_SUCCESS'
export const GET_CONFIG_ORG_ROLE_ERROR = 'GET_CONFIG_ORG_ROLE_ERROR'
export const CLEAR_GET_ORG_CONFIG_ORG_ROLE_INFO =
  'CLEAR_GET_ORG_CONFIG_ORG_ROLE_INFO'
export const GET_CONFIG_ENTERPRISE_ROLE = 'GET_CONFIG_ENTERPRISE_ROLE'
export const GET_CONFIG_ENTERPRISE_ROLE_SUCCESS =
  'GET_CONFIG_ENTERPRISE_ROLE_SUCCESS'
export const GET_CONFIG_ENTERPRISE_ROLE_ERROR =
  'GET_CONFIG_ENTERPRISE_ROLE_ERROR'

export const GET_CONFIG_SYSTEM_ROLE = 'GET_CONFIG_SYSTEM_ROLE'
export const GET_CONFIG_SYSTEM_ROLE_SUCCESS = 'GET_CONFIG_SYSTEM_ROLE_SUCCESS'
export const GET_CONFIG_SYSTEM_ROLE_ERROR = 'GET_CONFIG_SYSTEM_ROLE_ERROR'

export const GET_CONFIG_CLIENT_TYPE = 'GET_CONFIG_CLIENT_TYPES'
export const GET_CONFIG_CLIENT_TYPE_SUCCESS = 'GET_CONFIG_CLIENT_TYPES_SUCCESS'
export const GET_CONFIG_CLIENT_TYPE_ERROR = 'GET_CONFIG_CLIENT_TYPES_ERROR'

export const GET_CONFIG_DEVICE_TYPE = 'GET_CONFIG_DEVICE_TYPE'
export const GET_CONFIG_DEVICE_TYPE_SUCCESS = 'GET_CONFIG_DEVICE_TYPE_SUCCESS'
export const GET_CONFIG_DEVICE_TYPE_ERROR = 'GET_CONFIG_DEVICE_TYPE_ERROR'

export const GET_CONFIG_FEATURE_CLIENT = 'GET_CONFIG_FEATURE_CLIENT'
export const GET_CONFIG_FEATURE_CLIENT_SUCCESS =
  'GET_CONFIG_FEATURE_CLIENT_SUCCESS'
export const GET_CONFIG_FEATURE_CLIENT_ERROR = 'GET_CONFIG_FEATURE_CLIENT_ERROR'

export const GET_CONFIG_FEATURE_DEVICE = 'GET_CONFIG_FEATURE_DEVICE'
export const GET_CONFIG_FEATURE_DEVICE_SUCCESS =
  'GET_CONFIG_FEATURE_DEVICE_SUCCESS'
export const GET_CONFIG_FEATURE_DEVICE_ERROR = 'GET_CONFIG_FEATURE_DEVICE_ERROR'

export const GET_CONFIG_FEATURE_MEDIA = 'GET_CONFIG_FEATURE_MEDIA'
export const GET_CONFIG_FEATURE_MEDIA_SUCCESS =
  'GET_CONFIG_FEATURE_MEDIA_SUCCESS'
export const GET_CONFIG_FEATURE_MEDIA_ERROR = 'GET_CONFIG_FEATURE_MEDIA_ERROR'

export const GET_CONFIG_MEDIA_CATEGORY = 'GET_CONFIG_MEDIA_CATEGORY'
export const GET_CONFIG_MEDIA_CATEGORY_SUCCESS =
  'GET_CONFIG_MEDIA_CATEGORY_SUCCESS'
export const GET_CONFIG_MEDIA_CATEGORY_ERROR = 'GET_CONFIG_MEDIA_CATEGORY_ERROR'

export const GET_CONFIG_TRANSITIONS = 'GET_CONFIG_TRANSITIONS'
export const GET_CONFIG_TRANSITIONS_SUCCESS = 'GET_CONFIG_TRANSITIONS_SUCCESS'
export const GET_CONFIG_TRANSITIONS_ERROR = 'GET_CONFIG_TRANSITIONS_ERROR'

export const GET_CONFIG_ALERT_TYPES = 'GET_CONFIG_ALERT_TYPES'
export const GET_CONFIG_ALERT_TYPES_SUCCESS = 'GET_CONFIG_ALERT_TYPES_SUCCESS'
export const GET_CONFIG_ALERT_TYPES_ERROR = 'GET_CONFIG_ALERT_TYPES_ERROR'
export const CLEAR_GET_CONFIG_ALERT_TYPES_INFO =
  'CLEAR_GET_CONFIG_ALERT_TYPES_INFO'

export const GET_THEME_OF_MEDIA_FEATURE_BY_ID =
  'GET_THEME_OF_MEDIA_FEATURE_BY_ID'
export const GET_THEME_OF_MEDIA_FEATURE_BY_ID_SUCCESS =
  'GET_THEME_OF_MEDIA_FEATURE_BY_ID_SUCCESS'
export const GET_THEME_OF_MEDIA_FEATURE_BY_ID_ERROR =
  'GET_THEME_OF_MEDIA_FEATURE_BY_ID_ERROR'

export const GET_CONTENT_SOURCE_OF_MEDIA_FEATURE_BY_ID =
  'GET_CONTENT_SOURCE_OF_MEDIA_FEATURE_BY_ID'
export const GET_CONTENT_SOURCE_OF_MEDIA_FEATURE_BY_ID_SUCCESS =
  'GET_CONTENT_SOURCE_OF_MEDIA_FEATURE_BY_ID_SUCCESS'
export const GET_CONTENT_SOURCE_OF_MEDIA_FEATURE_BY_ID_ERROR =
  'GET_CONTENT_SOURCE_OF_MEDIA_FEATURE_BY_ID_ERROR'

export const GET_LOCATION_INFO = 'GET_LOCATION_INFO'
export const GET_LOCATION_INFO_SUCCESS = 'GET_LOCATION_INFO_SUCCESS'
export const GET_LOCATION_INFO_ERROR = 'GET_LOCATION_INFO_ERROR'

//Fonts Actions
export const GET_GOOGLE_FONTS = 'GET_GOOGLE_FONTS'
export const GET_GOOGLE_FONTS_SUCCESS = 'GET_GOOGLE_FONTS_SUCCESS'
export const GET_GOOGLE_FONTS_ERROR = 'GET_GOOGLE_FONTS_ERROR'

export const GET_SAVED_FONTS = 'GET_SAVED_FONTS'
export const GET_SAVED_FONTS_SUCCESS = 'GET_SAVED_FONTS_SUCCESS'
export const GET_SAVED_FONTS_ERROR = 'GET_SAVED_FONTS_ERROR'

export const EXTEND_FONTS_PER_PAGE = 'EXTEND_FONTS_PER_PAGE'
export const MERGE_WEB_FONT_CONFIG = 'MERGE_WEB_FONT_CONFIG'
export const ADD_FONTS_TO_LIST = 'ADD_FONTS_TO_LIST'
export const REMOVE_FONTS_TO_LIST = 'REMOVE_FONTS_TO_LIST'
export const CHANGE_VARIANT_OF_SELECTED_FONT = 'CHANGE_VARIANT_OF_SELECTED_FONT'
export const CLEAR_ADDED_FONTS = 'CLEAR_ADDED_FONTS'
export const DELETE_SAVED_FONTS = 'DELETE_SAVED_FONTS'
export const SET_FILTERS = 'SET_FILTERS'
export const SELECT_FONT = 'SELECT_FONT'
export const UNSELECT_FONT = 'UNSELECT_FONT'
export const SELECT_ALL_FONTS = 'SELECT_ALL_FONTS'
export const DELETE_SELECTED_FONTS = 'DELETE_SELECTED_FONTS'

//HTML Content Actions
export const GET_HTML_CONTENTS = 'GET_HTML_CONTENTS'
export const GET_HTML_CONTENTS_SUCCESS = 'GET_HTML_CONTENTS_SUCCESS'
export const GET_HTML_CONTENTS_ERROR = 'GET_HTML_CONTENTS_ERROR'

export const GET_HTML_CONTENT_BY_ID = 'GET_HTML_CONTENT_BY_ID'
export const GET_HTML_CONTENT_BY_ID_SUCCESS = 'GET_HTML_CONTENT_BY_ID_SUCCESS'
export const GET_HTML_CONTENT_BY_ID_ERROR = 'GET_HTML_CONTENT_BY_ID_ERROR'

export const POST_HTML_CONTENT = 'POST_HTML_CONTENT'
export const POST_HTML_CONTENT_SUCCESS = 'POST_HTML_CONTENT_SUCCESS'
export const POST_HTML_CONTENT_ERROR = 'POST_HTML_CONTENT_ERROR'

export const PUT_HTML_CONTENT = 'PUT_HTML_CONTENT'
export const PUT_HTML_CONTENT_SUCCESS = 'PUT_HTML_CONTENT_SUCCESS'
export const PUT_HTML_CONTENT_ERROR = 'PUT_HTML_CONTENT_ERROR'

export const DELETE_HTML_CONTENT = 'DELETE_HTML_CONTENT'
export const DELETE_HTML_CONTENT_SUCCESS = 'DELETE_HTML_CONTENT_SUCCESS'
export const DELETE_HTML_CONTENT_ERROR = 'DELETE_HTML_CONTENT_ERROR'

export const DELETE_SELECTED_HTML_CONTENTS = 'DELETE_SELECTED_HTML_CONTENTS'
export const DELETE_SELECTED_HTML_CONTENTS_SUCCESS =
  'DELETE_SELECTED_SELECTED_HTML_CONTENTS_SUCCESS'
export const DELETE_SELECTED_HTML_CONTENTS_ERROR =
  'DELETE_SELECTED_HTML_CONTENTS_ERROR'

export const CLEAR_HTML_CONTENT_RESPONSE_INFO =
  'CLEAR_HTML_CONTENT_RESPONSE_INFO'

//Settings Actions
export const PUT_CLIENT_SETTINGS = 'PUT_CLIENT_SETTINGS'
export const PUT_CLIENT_SETTINGS_SUCCESS = 'PUT_CLIENT_SETTINGS_SUCCESS'
export const PUT_CLIENT_SETTINGS_ERROR = 'PUT_CLIENT_SETTINGS_ERROR'
export const CLEAR_PUT_CLIENT_SETTINGS_INFO = 'CLEAR_PUT_CLIENT_SETTINGS_INFO'

export const GET_SETTINGS = 'GET_SETTINGS'
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS'
export const GET_SETTINGS_ERROR = 'GET_SETTINGS_ERROR'
export const CLEAR_SETTINGS = 'CLEAR_SETTINGS'
export const PUT_SETTINGS = 'PUT_SETTINGS'
export const PUT_SETTINGS_SUCCESS = 'PUT_SETTINGS_SUCCESS'
export const PUT_SETTINGS_ERROR = 'PUT_SETTINGS_ERROR'
export const CLEAR_PUT_SETTINGS_INFO = 'CLEAR_PUT_SETTINGS_INFO'

//Font Actions
export const GET_FONTS = 'GET_FONTS'
export const GET_FONTS_SUCCESS = 'GET_FONTS_SUCCESS'
export const GET_FONTS_ERROR = 'GET_FONTS_ERROR'
export const CLEAR_GET_FONTS_INFO = 'CLEAR_GET_FONTS_INFO'

export const DELETE_FONT = 'DELETE_FONT'
export const DELETE_FONT_SUCCESS = 'DELETE_FONT_SUCCESS'
export const DELETE_FONT_ERROR = 'DELETE_FONT_ERROR'
export const CLEAR_DELETE_FONT_INFO = 'CLEAR_DELETE_FONT_INFO'
export const POST_FONT = 'POST_FONT'
export const CLEAR_POST_FONT_INFO = 'CLEAR_POST_FONT_INFO'
export const POST_FONT_SUCCESS = 'POST_FONT_SUCCESS'
export const POST_FONT_ERROR = 'POST_FONT_ERROR'

//Banners Actions
export const GET_BANNERS = 'GET_BANNERS'
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS'
export const GET_BANNERS_ERROR = 'GET_BANNERS_ERROR'

export const GET_BANNER_BY_ID = 'GET_BANNER_BY_ID'
export const GET_BANNER_BY_ID_SUCCESS = 'GET_BANNER_BY_ID_SUCCESS'
export const GET_BANNER_BY_ID_ERROR = 'GET_BANNER_BY_ID_ERROR'

export const POST_BANNER = 'POST_BANNER'
export const POST_BANNER_SUCCESS = 'POST_BANNER_SUCCESS'
export const POST_BANNER_ERROR = 'POST_BANNER_ERROR'

export const PUT_BANNER = 'PUT_BANNER'
export const PUT_BANNER_SUCCESS = 'PUT_BANNER_SUCCESS'
export const PUT_BANNER_ERROR = 'PUT_BANNER_ERROR'

export const DELETE_BANNER = 'DELETE_BANNERS'
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNERS_SUCCESS'
export const DELETE_BANNER_ERROR = 'DELETE_BANNERS_ERROR'

export const DELETE_SELECTED_BANNERS = 'DELETE_SELECTED_BANNERS'
export const DELETE_SELECTED_BANNERS_SUCCESS =
  'DELETE_SELECTED_SELECTED_BANNERS_SUCCESS'
export const DELETE_SELECTED_BANNERS_ERROR = 'DELETE_SELECTED_BANNERS_ERROR'

export const CLEAR_BANNER_RESPONSE_INFO = 'CLEAR_BANNER_RESPONSE_INFO'

//Client Package Actions
export const GET_CLIENT_PACKAGES = 'GET_CLIENT_PACKAGES'
export const GET_CLIENT_PACKAGES_SUCCESS = 'GET_CLIENT_PACKAGES_SUCCESS'
export const GET_CLIENT_PACKAGES_ERROR = 'GET_CLIENT_PACKAGES_ERROR'

export const POST_CLIENT_PACKAGE = 'POST_CLIENT_PACKAGE'
export const POST_CLIENT_PACKAGE_SUCCESS = 'POST_CLIENT_PACKAGE_SUCCESS'
export const POST_CLIENT_PACKAGE_ERROR = 'POST_CLIENT_PACKAGE_ERROR'

export const GET_CLIENT_PACKAGE_BY_ID = 'GET_CLIENT_PACKAGE_BY_ID'
export const GET_CLIENT_PACKAGE_BY_ID_SUCCESS =
  'GET_CLIENT_PACKAGE_BY_ID_SUCCESS'
export const GET_CLIENT_PACKAGE_BY_ID_ERROR = 'GET_CLIENT_PACKAGE_BY_ID_ERROR'

export const PUT_CLIENT_PACKAGE = 'PUT_CLIENT_PACKAGE'
export const PUT_CLIENT_PACKAGE_SUCCESS = 'PUT_CLIENT_PACKAGE_SUCCESS'
export const PUT_CLIENT_PACKAGE_ERROR = 'PUT_CLIENT_PACKAGE_ERROR'

export const DELETE_CLIENT_PACKAGE = 'DELETE_CLIENT_PACKAGE'
export const DELETE_CLIENT_PACKAGE_SUCCESS = 'DELETE_CLIENT_PACKAGE_SUCCESS'
export const DELETE_CLIENT_PACKAGE_ERROR = 'DELETE_CLIENT_PACKAGE_ERROR'

export const DELETE_SELECTED_CLIENT_PACKAGES = 'DELETE_SELECTED_CLIENT_PACKAGES'
export const DELETE_SELECTED_CLIENT_PACKAGES_SUCCESS =
  'DELETE_SELECTED_SELECTED_CLIENT_PACKAGES_SUCCESS'
export const DELETE_SELECTED_CLIENT_PACKAGES_ERROR =
  'DELETE_SELECTED_CLIENT_PACKAGES_ERROR'

export const CLEAR_CLIENT_PACKAGE_RESPONSE_INFO =
  'CLEAR_CLIENT_PACKAGE_RESPONSE_INFO'

//Device Package
export const GET_DEVICE_PACKAGES = 'GET_DEVICE_PACKAGES'
export const GET_DEVICE_PACKAGES_SUCCESS = 'GET_DEVICE_PACKAGES_SUCCESS'
export const GET_DEVICE_PACKAGES_ERROR = 'GET_DEVICE_PACKAGES_ERROR'

export const GET_DEVICE_PACKAGE_BY_ID = 'GET_DEVICE_PACKAGE_BY_ID'
export const GET_DEVICE_PACKAGE_BY_ID_SUCCESS =
  'GET_DEVICE_PACKAGE_BY_ID_SUCCESS'
export const GET_DEVICE_PACKAGE_BY_ID_ERROR = 'GET_DEVICE_PACKAGE_BY_ID_ERROR'

export const DELETE_DEVICE_PACKAGE = 'DELETE_DEVICE_PACKAGE'
export const DELETE_DEVICE_PACKAGE_SUCCESS = 'DELETE_DEVICE_PACKAGE_SUCCESS'
export const DELETE_DEVICE_PACKAGE_ERROR = 'DELETE_DEVICE_PACKAGE_ERROR'

export const POST_DEVICE_PACKAGE = 'POST_DEVICE_PACKAGE'
export const POST_DEVICE_PACKAGE_SUCCESS = 'POST_DEVICE_PACKAGE_SUCCESS'
export const POST_DEVICE_PACKAGE_ERROR = 'POST_DEVICE_PACKAGE_ERROR'

export const PUT_DEVICE_PACKAGE = 'PUT_DEVICE_PACKAGE'
export const PUT_DEVICE_PACKAGE_SUCCESS = 'PUT_DEVICE_PACKAGE_SUCCESS'
export const PUT_DEVICE_PACKAGE_ERROR = 'PUT_DEVICE_PACKAGE_ERROR'

export const DELETE_SELECTED_DEVICE_PACKAGES = 'DELETE_SELECTED_DEVICE_PACKAGES'
export const DELETE_SELECTED_DEVICE_PACKAGES_SUCCESS =
  'DELETE_SELECTED_SELECTED_DEVICE_PACKAGES_SUCCESS'
export const DELETE_SELECTED_DEVICE_PACKAGES_ERROR =
  'DELETE_SELECTED_DEVICE_PACKAGES_ERROR'

export const CLEAR_DEVICE_PACKAGE_RESPONSE_INFO =
  'CLEAR_DEVICE_PACKAGE_RESPONSE_INFO'

//Device Package actions
export const GET_BANDWIDTH_PACKAGES = 'GET_BANDWIDTH_PACKAGES'
export const GET_BANDWIDTH_PACKAGES_SUCCESS = 'GET_BANDWIDTH_PACKAGES_SUCCESS'
export const GET_BANDWIDTH_PACKAGES_ERROR = 'GET_BANDWIDTH_PACKAGES_ERROR'

export const GET_BANDWIDTH_PACKAGE_BY_ID = 'GET_BANDWIDTH_PACKAGE_BY_ID'
export const GET_BANDWIDTH_PACKAGE_BY_ID_SUCCESS =
  'GET_BANDWIDTH_PACKAGE_BY_ID_SUCCESS'
export const GET_BANDWIDTH_PACKAGE_BY_ID_ERROR =
  'GET_BANDWIDTH_PACKAGE_BY_ID_ERROR'

export const DELETE_BANDWIDTH_PACKAGE = 'DELETE_BANDWIDTH_PACKAGE'
export const DELETE_BANDWIDTH_PACKAGE_SUCCESS =
  'DELETE_BANDWIDTH_PACKAGE_SUCCESS'
export const DELETE_BANDWIDTH_PACKAGE_ERROR = 'DELETE_BANDWIDTH_PACKAGE_ERROR'

export const POST_BANDWIDTH_PACKAGE = 'POST_BANDWIDTH_PACKAGE'
export const POST_BANDWIDTH_PACKAGE_SUCCESS = 'POST_BANDWIDTH_PACKAGE_SUCCESS'
export const POST_BANDWIDTH_PACKAGE_ERROR = 'POST_BANDWIDTH_PACKAGE_ERROR'

export const PUT_BANDWIDTH_PACKAGE = 'PUT_BANDWIDTH_PACKAGE'
export const PUT_BANDWIDTH_PACKAGE_SUCCESS = 'PUT_BANDWIDTH_PACKAGE_SUCCESS'
export const PUT_BANDWIDTH_PACKAGE_ERROR = 'PUT_BANDWIDTH_PACKAGE_ERROR'

export const DELETE_SELECTED_BANDWIDTH_PACKAGES =
  'DELETE_SELECTED_BANDWIDTH_PACKAGES'
export const DELETE_SELECTED_BANDWIDTH_PACKAGES_SUCCESS =
  'DELETE_SELECTED_SELECTED_BANDWIDTH_PACKAGES_SUCCESS'
export const DELETE_SELECTED_BANDWIDTH_PACKAGES_ERROR =
  'DELETE_SELECTED_BANDWIDTH_PACKAGES_ERROR'

export const CLEAR_BANDWIDTH_PACKAGE_RESPONSE_INFO =
  'CLEAR_BANDWIDTH_PACKAGE_RESPONSE_INFO'

//Email Templates actions
export const GET_EMAIL_TEMPLATES = 'GET_EMAIL_TEMPLATES'
export const GET_EMAIL_TEMPLATES_SUCCESS = 'GET_EMAIL_TEMPLATES_SUCCESS'
export const GET_EMAIL_TEMPLATES_ERROR = 'GET_EMAIL_TEMPLATES_ERROR'

export const GET_EMAIL_TEMPLATE_BY_ID = 'GET_EMAIL_TEMPLATE_BY_ID'
export const GET_EMAIL_TEMPLATE_BY_ID_SUCCESS =
  'GET_EMAIL_TEMPLATE_BY_ID_SUCCESS'
export const GET_EMAIL_TEMPLATE_BY_ID_ERROR = 'GET_EMAIL_TEMPLATE_BY_ID_ERROR'

export const PUT_EMAIL_TEMPLATE = 'PUT_EMAIL_TEMPLATE'
export const PUT_EMAIL_TEMPLATE_SUCCESS = 'PUT_EMAIL_TEMPLATE_SUCCESS'
export const PUT_EMAIL_TEMPLATE_ERROR = 'PUT_EMAIL_TEMPLATE_ERROR'

export const CLEAR_EMAIL_TEMPLATE_RESPONSE_INFO =
  'CLEAR_EMAIL_TEMPLATE_RESPONSE_INFO'

//Email Templates actions
export const GET_CUSTOM_EMAIL_TEMPLATES = 'GET_CUSTOM_EMAIL_TEMPLATES'
export const GET_CUSTOM_EMAIL_TEMPLATES_SUCCESS =
  'GET_CUSTOM_EMAIL_TEMPLATES_SUCCESS'
export const GET_CUSTOM_EMAIL_TEMPLATES_ERROR =
  'GET_CUSTOM_EMAIL_TEMPLATES_ERROR'

export const GET_CUSTOM_EMAIL_TEMPLATE_BY_ID = 'GET_CUSTOM_EMAIL_TEMPLATE_BY_ID'
export const GET_CUSTOM_EMAIL_TEMPLATE_BY_ID_SUCCESS =
  'GET_CUSTOM_EMAIL_TEMPLATE_BY_ID_SUCCESS'
export const GET_CUSTOM_EMAIL_TEMPLATE_BY_ID_ERROR =
  'GET_CUSTOM_EMAIL_TEMPLATE_BY_ID_ERROR'

export const PUT_CUSTOM_EMAIL_TEMPLATE = 'PUT_CUSTOM_EMAIL_TEMPLATE'
export const PUT_CUSTOM_EMAIL_TEMPLATE_SUCCESS =
  'PUT_CUSTOM_EMAIL_TEMPLATE_SUCCESS'
export const PUT_CUSTOM_EMAIL_TEMPLATE_ERROR = 'PUT_CUSTOM_EMAIL_TEMPLATE_ERROR'

export const POST_CUSTOM_EMAIL_TEMPLATE = 'POST_CUSTOM_EMAIL_TEMPLATE'
export const POST_CUSTOM_EMAIL_TEMPLATE_SUCCESS =
  'POST_CUSTOM_EMAIL_TEMPLATE_SUCCESS'
export const POST_CUSTOM_EMAIL_TEMPLATE_ERROR =
  'POST_CUSTOM_EMAIL_TEMPLATE_ERROR'

export const CLEAR_CUSTOM_EMAIL_TEMPLATE_RESPONSE_INFO =
  'CLEAR_CUSTOM_EMAIL_TEMPLATE_RESPONSE_INFO'

// Help Actions
export const GET_HELPS = 'GET_HELPS'
export const GET_HELPS_SUCCESS = 'GET_HELPS_SUCCESS'
export const GET_HELPS_ERROR = 'GET_HELPS_ERROR'

export const PUT_HELP = 'PUT_HELP'
export const PUT_HELP_SUCCESS = 'PUT_HELP_SUCCESS'
export const PUT_HELP_ERROR = 'PUT_HELP_ERROR'

export const CLEAR_HELP_RESPONSE_INFO = 'CLEAR_HELP_RESPONSE_INFO'

//Category Actions

export const GET_CATEGORIES_BY_FEATURE = 'GET_CATEGORIES_BY_FEATURE'
export const GET_CATEGORIES_BY_FEATURE_SUCCESS =
  'GET_CATEGORIES_BY_FEATURE_SUCCESS'
export const GET_CATEGORIES_BY_FEATURE_ERROR = 'GET_CATEGORIES_BY_FEATURE_ERROR'

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID'
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS'
export const GET_CATEGORY_BY_ID_ERROR = 'GET_CATEGORY_BY_ID_ERROR'

export const PUT_CATEGORY = 'PUT_CATEGORY'
export const PUT_CATEGORY_SUCCESS = 'PUT_CATEGORY_SUCCESS'
export const PUT_CATEGORY_ERROR = 'PUT_CATEGORY_ERROR'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR'

export const POST_CATEGORY_INTO_FEATURE = 'POST_CATEGORY_INTO_FEATURE'
export const POST_CATEGORY_INTO_FEATURE_SUCCESS =
  'POST_CATEGORY_INTO_FEATURE_SUCCESS'
export const POST_CATEGORY_INTO_FEATURE_ERROR =
  'POST_CATEGORY_INTO_FEATURE_ERROR'

export const CLEAR_CATEGORY_RESPONSE_INFO = 'CLEAR_CATEGORY_RESPONSE_INFO'

//Content Actions

export const GET_CONTENTS_BY_FEATURE = 'GET_CONTENTS_BY_FEATURE'
export const GET_CONTENTS_BY_FEATURE_SUCCESS = 'GET_CONTENTS_BY_FEATURE_SUCCESS'
export const GET_CONTENTS_BY_FEATURE_ERROR = 'GET_CONTENTS_BY_FEATURE_ERROR'

export const GET_CONTENT_BY_ID = 'GET_CONTENT_BY_ID'
export const GET_CONTENT_BY_ID_SUCCESS = 'GET_CONTENT_BY_ID_SUCCESS'
export const GET_CONTENT_BY_ID_ERROR = 'GET_CONTENT_BY_ID_ERROR'

export const PUT_CONTENT = 'PUT_CONTENT'
export const PUT_CONTENT_SUCCESS = 'PUT_CONTENT_SUCCESS'
export const PUT_CONTENT_ERROR = 'PUT_CONTENT_ERROR'

export const DELETE_CONTENT = 'DELETE_CONTENT'
export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS'
export const DELETE_CONTENT_ERROR = 'DELETE_CONTENT_ERROR'

export const DELETE_SELECTED_CONTENT = 'DELETE_SELECTED_CONTENT'
export const DELETE_SELECTED_CONTENT_SUCCESS = 'DELETE_SELECTED_CONTENT_SUCCESS'
export const DELETE_SELECTED_CONTENT_ERROR = 'DELETE_SELECTED_CONTENT_ERROR'

export const POST_CONTENT_INTO_FEATURE = 'POST_CONTENT_INTO_FEATURE'
export const POST_CONTENT_INTO_FEATURE_SUCCESS =
  'POST_CONTENT_INTO_FEATURE_SUCCESS'
export const POST_CONTENT_INTO_FEATURE_ERROR = 'POST_CONTENT_INTO_FEATURE_ERROR'

export const CLEAR_CONTENT_RESPONSE_INFO = 'CLEAR_CONTENT_RESPONSE_INFO'

//Role Actions

export const GET_ROLES = 'GET_ROLES'
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
export const GET_ROLES_ERROR = 'GET_ROLES_ERROR'
export const CLEAR_GET_ROLES_INFO = 'CLEAR_GET_ROLES_INFO'

export const GET_ROLE_BY_ID = 'GET_ROLE_BY_ID'
export const GET_ROLE_BY_ID_SUCCESS = 'GET_ROLE_BY_ID_SUCCESS'
export const GET_ROLE_BY_ID_ERROR = 'GET_ROLE_BY_ID_ERROR'
export const CLEAR_GET_ROLE_BY_ID_INFO = 'CLEAR_GET_ROLE_BY_ID_INFO'

export const POST_ROLE = 'POST_ROLE'
export const POST_ROLE_SUCCESS = 'POST_ROLE_SUCCESS'
export const POST_ROLE_ERROR = 'POST_ROLE_ERROR'
export const CLEAR_POST_ROLE_INFO = 'CLEAR_POST_ROLE_INFO'

export const PUT_ROLE_BY_ID = 'PUT_ROLE_BY_ID'
export const PUT_ROLE_BY_ID_SUCCESS = 'PUT_ROLE_BY_ID_SUCCESS'
export const PUT_ROLE_BY_ID_ERROR = 'PUT_ROLE_BY_ID_ERROR'
export const CLEAR_PUT_ROLE_INFO = 'CLEAR_PUT_ROLE_INFO'

export const GET_ROLE_PERMISSION_BY_ID = 'GET_ROLE_PERMISSION_BY_ID'
export const GET_ROLE_PERMISSION_BY_ID_SUCCESS =
  'GET_ROLE_PERMISSION_BY_ID_SUCCESS'
export const GET_ROLE_PERMISSION_BY_ID_ERROR = 'GET_ROLE_PERMISSION_BY_ID_ERROR'
export const CLEAR_GET_ROLE_PERMISSION_BY_ID_INFO =
  'CLEAR_GET_ROLE_PERMISSION_BY_ID_INFO'

export const PUT_ROLE_PERMISSION_BY_ID = 'PUT_ROLE_PERMISSION_BY_ID'
export const PUT_ROLE_PERMISSION_BY_ID_SUCCESS =
  'PUT_ROLE_PERMISSION_BY_ID_SUCCESS'
export const PUT_ROLE_PERMISSION_BY_ID_ERROR = 'PUT_ROLE_PERMISSION_BY_ID_ERROR'
export const CLEAR_PUT_ROLE_PERMISSION_BY_ID_INFO =
  'CLEAR_PUT_ROLE_PERMISSION_BY_ID_INFO'

//Announcement actions

export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS'
export const GET_ANNOUNCEMENTS_SUCCESS = 'GET_ANNOUNCEMENTS_SUCCESS'
export const GET_ANNOUNCEMENTS_ERROR = 'GET_ANNOUNCEMENTS_ERROR'

export const POST_ANNOUNCEMENT = 'POST_ANNOUNCEMENT'
export const POST_ANNOUNCEMENT_SUCCESS = 'POST_ANNOUNCEMENT_SUCCESS'
export const POST_ANNOUNCEMENT_ERROR = 'POST_ANNOUNCEMENT_ERROR'

export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT'
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS'
export const DELETE_ANNOUNCEMENT_ERROR = 'DELETE_ANNOUNCEMENT_ERROR'

export const GET_ANNOUNCEMENT = 'GET_ANNOUNCEMENT'
export const GET_ANNOUNCEMENT_SUCCESS = 'GET_ANNOUNCEMENT_SUCCESS'
export const GET_ANNOUNCEMENT_ERROR = 'GET_ANNOUNCEMENT_ERROR'

export const PUT_ANNOUNCEMENT = 'PUT_ANNOUNCEMENT'
export const PUT_ANNOUNCEMENT_SUCCESS = 'PUT_ANNOUNCEMENT_SUCCESS'
export const PUT_ANNOUNCEMENT_ERROR = 'PUT_ANNOUNCEMENT_ERROR'

export const CLEAR_ANNOUNCEMENTS_RESPONSE_INFO =
  'CLEAR_ANNOUNCEMENTS_RESPONSE_INFO'

export const DELETE_SELECTED_ANNOUNCEMENTS_SUCCESS =
  'DELETE_SELECTED_ANNOUNCEMENTS_SUCCESS'
export const DELETE_SELECTED_ANNOUNCEMENTS_ERROR =
  'DELETE_SELECTED_ANNOUNCEMENTS_ERROR'
export const DELETE_SELECTED_ANNOUNCEMENT = 'DELETE_SELECTED_ANNOUNCEMENT'

//Workplace Poster actions

export const GET_WORKPLACE_POSTERS = 'GET_WORKPLACE_POSTERS'
export const GET_WORKPLACE_POSTERS_SUCCESS = 'GET_WORKPLACE_POSTERS_SUCCESS'
export const GET_WORKPLACE_POSTERS_ERROR = 'GET_WORKPLACE_POSTERS_ERROR'

export const POST_WORKPLACE_POSTER = 'POST_WORKPLACE_POSTER'
export const POST_WORKPLACE_POSTER_SUCCESS = 'POST_WORKPLACE_POSTER_SUCCESS'
export const POST_WORKPLACE_POSTER_ERROR = 'POST_WORKPLACE_POSTER_ERROR'

export const DELETE_WORKPLACE_POSTER = 'DELETE_WORKPLACE_POSTER'
export const DELETE_WORKPLACE_POSTER_SUCCESS = 'DELETE_WORKPLACE_POSTER_SUCCESS'
export const DELETE_WORKPLACE_POSTER_ERROR = 'DELETE_WORKPLACE_POSTER_ERROR'

export const GET_WORKPLACE_POSTER = 'GET_WORKPLACE_POSTER'
export const GET_WORKPLACE_POSTER_SUCCESS = 'GET_WORKPLACE_POSTER_SUCCESS'
export const GET_WORKPLACE_POSTER_ERROR = 'GET_WORKPLACE_POSTER_ERROR'

export const PUT_WORKPLACE_POSTER = 'PUT_WORKPLACE_POSTER'
export const PUT_WORKPLACE_POSTER_SUCCESS = 'PUT_WORKPLACE_POSTER_SUCCESS'
export const PUT_WORKPLACE_POSTER_ERROR = 'PUT_WORKPLACE_POSTER_ERROR'

export const CLEAR_WORKPLACE_POSTERS_RESPONSE_INFO =
  'CLEAR_WORKPLACE_POSTERS_RESPONSE_INFO'

export const DELETE_SELECTED_WORKPLACE_POSTERS_SUCCESS =
  'DELETE_SELECTED_WORKPLACE_POSTERS_SUCCESS'
export const DELETE_SELECTED_WORKPLACE_POSTERS_ERROR =
  'DELETE_SELECTED_WORKPLACE_POSTERS_ERROR'
export const DELETE_SELECTED_WORKPLACE_POSTER =
  'DELETE_SELECTED_WORKPLACE_POSTER'

export const GET_WORKPLACE_POSTERS_TAGS = 'GET_WORKPLACE_POSTERS_TAGS'
export const GET_WORKPLACE_POSTERS_TAGS_SUCCESS =
  'GET_WORKPLACE_POSTERS_TAGS_SUCCESS'
export const GET_WORKPLACE_POSTERS_TAGS_ERROR =
  'GET_WORKPLACE_POSTERS_TAGS_ERROR'

export const POST_WORKPLACE_POSTER_TAG = 'POST_WORKPLACE_POSTER_TAG'
export const POST_WORKPLACE_POSTER_TAG_SUCCESS =
  'POST_WORKPLACE_POSTER_TAG_SUCCESS'
export const POST_WORKPLACE_POSTER_TAG_ERROR = 'POST_WORKPLACE_POSTER_TAG_ERROR'

export const DELETE_WORKPLACE_POSTER_TAG = 'DELETE_WORKPLACE_POSTER_TAG'
export const DELETE_WORKPLACE_POSTER_TAG_SUCCESS =
  'DELETE_WORKPLACE_POSTER_TAG_SUCCESS'
export const DELETE_WORKPLACE_POSTER_TAG_ERROR =
  'DELETE_WORKPLACE_POSTER_TAG_ERROR'

// Preference Actions

export const GET_PREFERENCE_BY_ENTITY = 'GET_PREFERENCE_BY_ENTITY'
export const GET_PREFERENCE_BY_ENTITY_SUCCESS =
  'GET_PREFERENCE_BY_ENTITY_SUCCESS'
export const GET_PREFERENCE_BY_ENTITY_ERROR = 'GET_PREFERENCE_BY_ENTITY_ERROR'

export const PUT_PREFERENCE_BY_ENTITY = 'PUT_PREFERENCE_BY_ENTITY'
export const PUT_PREFERENCE_BY_ENTITY_SUCCESS =
  'PUT_PREFERENCE_BY_ENTITY_SUCCESS'
export const PUT_PREFERENCE_BY_ENTITY_ERROR = 'PUT_PREFERENCE_BY_ENTITY_ERROR'

export const CLEAR_THEME_OF_MEDIA = 'CLEAR_THEME_OF_MEDIA'
export const CLEAR_THEME_OF_MEDIA_SUCCESS = 'CLEAR_THEME_OF_MEDIA_SUCCESS'

//Client Users Actions
export const GET_CLIENT_USERS_ITEMS = 'GET_CLIENT_USERS_ITEMS'
export const GET_CLIENT_USERS_ITEMS_SUCCESS = 'GET_CLIENT_USERS_ITEMS_SUCCESS'
export const GET_CLIENT_USERS_ITEMS_ERROR = 'GET_CLIENT_USERS_ITEMS_ERROR'

export const POST_CLIENT_USERS_ITEM = 'POST_CLIENT_USERS_ITEM'
export const POST_CLIENT_USERS_ITEM_SUCCESS = 'POST_CLIENT_USERS_ITEM_SUCCESS'
export const POST_CLIENT_USERS_ITEM_ERROR = 'POST_CLIENT_USERS_ITEM_ERROR'

export const DELETE_CLIENT_USERS_ITEM = 'DELETE_CLIENT_USERS_ITEM'
export const DELETE_CLIENT_USERS_ITEM_SUCCESS =
  'DELETE_CLIENT_USERS_ITEM_SUCCESS'
export const DELETE_CLIENT_USERS_ITEM_ERROR = 'DELETE_CLIENT_USERS_ITEM_ERROR'

export const DELETE_SELECTED_CLIENT_USERS = 'DELETE_SELECTED_CLIENT_USERS'
export const DELETE_SELECTED_CLIENT_USERS_SUCCESS =
  'DELETE_SELECTED_CLIENT_USERS_SUCCESS'
export const DELETE_SELECTED_CLIENT_USERS_ERROR =
  'DELETE_SELECTED_CLIENT_USERS_ERROR'

export const GET_CLIENT_USERS_ITEM = 'GET_CLIENT_USERS_ITEM'
export const GET_CLIENT_USERS_ITEM_SUCCESS = 'GET_CLIENT_USERS_ITEM_SUCCESS'
export const GET_CLIENT_USERS_ITEM_ERROR = 'GET_CLIENT_USERS_ITEM_ERROR'

export const PUT_CLIENT_USERS_ITEM = 'PUT_CLIENT_USERS_ITEM'
export const PUT_CLIENT_USERS_ITEM_SUCCESS = 'PUT_CLIENT_USERS_ITEM_SUCCESS'
export const PUT_CLIENT_USERS_ITEM_ERROR = 'PUT_CLIENT_USERS_ITEM_ERROR'

export const CLEAR_CLIENT_USERS_RESPONSE_INFO =
  'CLEAR_CLIENT_USERS_RESPONSE_INFO'

export const GET_WHITE_LABEL = 'GET_WHITE_LABEL'
export const GET_WHITE_LABEL_SUCCESS = 'GET_WHITE_LABEL_SUCCESS'
export const GET_WHITE_LABEL_ERROR = 'GET_WHITE_LABEL_ERROR'
export const CLEAR_GET_WHITE_LABEL_INFO = 'CLEAR_GET_WHITE_LABEL_INFO'
export const SET_WHITE_LABEL = 'SET_WHITE_LABEL'

export const GET_ALERT_DEVICES_BY_ID = 'GET_ALERT_DEVICES_BY_ID'
export const GET_ALERT_DEVICES_BY_ID_SUCCESS = 'GET_ALERT_DEVICES_BY_ID_SUCCESS'
export const GET_ALERT_DEVICES_BY_ID_ERROR = 'GET_ALERT_DEVICES_BY_ID_ERROR'
export const CLEAR_GET_ALERT_DEVICES_BY_ID_INFO =
  'CLEAR_GET_ALERT_DEVICES_BY_ID_INFO'
export const POST_ALERT_TRIGGER = 'POST_ALERT_TRIGGER'
export const POST_ALERT_TRIGGER_SUCCESS = 'POST_ALERT_TRIGGER_SUCCESS'
export const POST_ALERT_TRIGGER_ERROR = 'POST_ALERT_TRIGGER_ERROR'
export const CLEAR_POST_ALERT_TRIGGER_INFO = 'CLEAR_POST_ALERT_TRIGGER_INFO'

export const DISABLE_ALERT = 'DISABLE_ALERT'
export const DISABLE_ALERT_SUCCESS = 'DISABLE_ALERT_SUCCESS'
export const DISABLE_ALERT_ERROR = 'DISABLE_ALERT_ERROR'
export const CLEAR_DISABLE_ALERT_INFO = 'CLEAR_DISABLE_ALERT_INFO'

export const GET_DEVICE_MEDIA_EMERGENCY_ALERT =
  'GET_DEVICE_MEDIA_EMERGENCY_ALERT'
export const GET_DEVICE_MEDIA_EMERGENCY_ALERT_SUCCESS =
  'GET_DEVICE_MEDIA_EMERGENCY_ALERT_SUCCESS'
export const GET_DEVICE_MEDIA_EMERGENCY_ALERT_ERROR =
  'GET_DEVICE_MEDIA_EMERGENCY_ALERT_ERROR'
export const CLEAR_GET_DEVICE_MEDIA_EMERGENCY_ALERT_INFO =
  'CLEAR_GET_DEVICE_MEDIA_EMERGENCY_ALERT_INFO'

export const PUT_DEVICE_MEDIA_EMERGENCY_ALERT =
  'PUT_DEVICE_MEDIA_EMERGENCY_ALERT'
export const PUT_DEVICE_MEDIA_EMERGENCY_ALERT_SUCCESS =
  'PUT_DEVICE_MEDIA_EMERGENCY_ALERT_SUCCESS'
export const PUT_DEVICE_MEDIA_EMERGENCY_ALERT_ERROR =
  'PUT_DEVICE_MEDIA_EMERGENCY_ALERT_ERROR'
export const CLEAR_PUT_DEVICE_MEDIA_EMERGENCY_ALERT_INFO =
  'CLEAR_PUT_DEVICE_MEDIA_EMERGENCY_ALERT_INFO'

export const GET_DEVICE_MEDIA_CAP_ALERT = 'GET_DEVICE_MEDIA_CAP_ALERT'
export const GET_DEVICE_MEDIA_CAP_ALERT_SUCCESS =
  'GET_DEVICE_MEDIA_CAP_ALERT_SUCCESS'
export const GET_DEVICE_MEDIA_CAP_ALERT_ERROR =
  'GET_DEVICE_MEDIA_CAP_ALERT_ERROR'
export const CLEAR_GET_DEVICE_MEDIA_CAP_ALERT_INFO =
  'CLEAR_GET_DEVICE_MEDIA_CAP_ALERT_INFO'
export const PUT_DEVICE_MEDIA_CAP_ALERT = 'PUT_DEVICE_MEDIA_CAP_ALERT'
export const PUT_DEVICE_MEDIA_CAP_ALERT_SUCCESS =
  'PUT_DEVICE_MEDIA_CAP_ALERT_SUCCESS'
export const PUT_DEVICE_MEDIA_CAP_ALERT_ERROR =
  'PUT_DEVICE_MEDIA_CAP_ALERT_ERROR'
export const CLEAR_PUT_DEVICE_MEDIA_CAP_ALERT_INFO =
  'CLEAR_PUT_DEVICE_MEDIA_CAP_ALERT_INFO'
export const DISABLE_DEVICE_ALERT = 'DISABLE_DEVICE_ALERT'
export const DISABLE_DEVICE_ALERT_SUCCESS = 'DISABLE_DEVICE_ALERT_SUCCESS'
export const DISABLE_DEVICE_ALERT_ERROR = 'DISABLE_DEVICE_ALERT_ERROR'
export const CLEAR_DISABLE_DEVICE_ALERT_INFO = 'CLEAR_DISABLE_DEVICE_ALERT_INFO'

export const GET_FEATURE_MEDIA_ITEMS = 'GET_FEATURE_MEDIA_ITEMS'
export const GET_FEATURE_MEDIA_ITEMS_SUCCESS = 'GET_FEATURE_MEDIA_ITEMS_SUCCESS'
export const GET_FEATURE_MEDIA_ITEMS_ERROR = 'GET_FEATURE_MEDIA_ITEMS_ERROR'
export const CLEAR_GET_FEATURE_MEDIA_ITEMS_INFO =
  'CLEAR_GET_FEATURE_MEDIA_ITEMS_INFO'

//Quote Actions

export const GET_QUOTES = 'GET_QUOTES'
export const GET_QUOTES_SUCCESS = 'GET_QUOTES_SUCCESS'
export const GET_QUOTES_ERROR = 'GET_QUOTES_ERROR'
export const CLEAR_GET_QUOTES_INFO = 'CLEAR_GET_QUOTES_INFO'

export const POST_QUOTE = 'POST_QUOTE'
export const POST_QUOTE_SUCCESS = 'POST_QUOTE_SUCCESS'
export const POST_QUOTE_ERROR = 'POST_QUOTE_ERROR'
export const CLEAR_POST_QUOTE_INFO = 'CLEAR_POST_QUOTE_INFO'

export const GET_QUOTE_CATEGORIES = 'GET_QUOTE_CATEGORIES'
export const GET_QUOTE_CATEGORIES_SUCCESS = 'GET_QUOTE_CATEGORIES_SUCCESS'
export const GET_QUOTE_CATEGORIES_ERROR = 'GET_QUOTE_CATEGORIES_ERROR'
export const CLEAR_GET_QUOTE_CATEGORIES_INFO = 'CLEAR_GET_QUOTE_CATEGORIES_INFO'

export const GET_DESIGN_GALLERY = 'GET_DESIGN_GALLERY'
export const GET_DESIGN_GALLERY_SUCCESS = 'GET_DESIGN_GALLERY_SUCCESS'
export const GET_DESIGN_GALLERY_ERROR = 'GET_DESIGN_GALLERY_ERROR'
export const POST_DESIGN_GALLERY = 'POST_DESIGN_GALLERY'
export const POST_DESIGN_GALLERY_SUCCESS = 'POST_DESIGN_GALLERY_SUCCESS'
export const POST_DESIGN_GALLERY_ERROR = 'POST_DESIGN_GALLERY_ERROR'
export const PUT_DESIGN_GALLERY = 'PUT_DESIGN_GALLERY'
export const PUT_DESIGN_GALLERY_SUCCESS = 'PUT_DESIGN_GALLERY_SUCCESS'
export const PUT_DESIGN_GALLERY_ERROR = 'PUT_DESIGN_GALLERY_ERROR'
export const CLEAR_DESIGN_GALLERY = 'CLEAR_DESIGN_GALLERY'
export const CLEAR_DESIGN_GALLERY_STATUS = 'CLEAR_DESIGN_GALLERY_STATUS'
export const SET_HEIGHT_COMPONENT = 'SET_HEIGHT_COMPONENT'
