export default {
  mon: 'mon',
  tue: 'tue',
  wed: 'wed',
  thu: 'thu',
  fri: 'fri',
  sat: 'sat',
  sun: 'sun',
  weekly: 'weekly',
  monthly: 'monthly',
  everyYear: 'everyYear',
  other: 'other',
  custom: 'custom',
  daily: 'daily',
  never: 'never',
  week: 'week',
  month: 'month',
  after: 'after',
  date: 'date',
  day: 'day',
  interval: 'interval',
  countRepeat: 'countRepeat',
  monthlyDay: 'monthlyDay',
  monthlyDayOfWeek: 'monthlyDayOfWeek'
}
